# Generated by Django 4.0.2 on 2022-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='post_author',
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
